export const productos = [
    {
        id:1,
        title:"Agave Attenuata",
        price:"4550",
        description:"Agave attenuata, comúnmente llamada ágave atenuado, ágave del dragón o cuello de cisne, es una especie suculenta perteneciente a la familia de las agaváceas. Sus tallos alcanzan los 50 a 150 cm de longitud, eventualmente sus hojas viejas caen dejándolo desnudo y visible. Las hojas son ovadas, acuminadas de 70 cm de longitud y 12-16 cm de ancho, de color gris a amarillo-verdoso, pálidas y sin espinas. La inflorescencia es un racimo denso de 2,5 a 3 metros de altura, con flores de color amarillo-verdoso.",
        image:"agaveattenuata.jpg",
        stock: 7,
        category:1
    },
    {
        id:2,
        title:"Alegria Nueva Guinea",
        price:"3580",
        description:"Es una planta originaria de Nueva Guinea de tallos carnosos con hojas de color verde claro. Las flores varían mucho debido a la gran cantidad de variedades que hay. La Alegría guineana debe cultivarse en exposiciones con claridad pero sin sol directo o en semisombra. Son sensibles al frío por lo que se cultivan como planta de temporada.",
        image:"alegrianuevaguinea.jpg",
        stock: 0,
        category:1
    },
    {
        id:3, 
        title:"Aloe Vera", 
        price:"5510", 
        description:"Aloe vera, llamado sábila, acíbar o áloe de Barbados, entre otros, es una especie suculenta de la familia Asphodelaceae. Es una planta de hoja perenne, probablemente se originó en la Península Arábica, pero crece de forma silvestre en climas tropicales, semitropicales y áridos de todo el mundo. Se cultiva para productos comerciales, principalmente como tratamiento tópico utilizado durante siglos. La especie es atractiva con fines decorativos y tiene éxito en interiores como planta de maceta.", 
        image:"aloevera.jpg",
        stock: 17, 
        category:1
    },
    {
        id:4, 
        title:"Anthurium Andreanum", 
        price:"7500", 
        description:"", 
        image:"anthuriumandreanum.jpg",
        stock: 15, 
        category:1
    },
    {
        id:5, 
        title:"Anthurium Coriaceum", 
        price:"4800", 
        description:"", 
        image:"anthuriumcoriaceum.jpg", 
        stock: 10,
        category:1
    },
    {
        id:6, 
        title:"Aralia Japonica", 
        price:"4500", 
        description:"", 
        image:"araliajaponica.jpg", 
        stock: 8,
        category:1
    },
    {
        id:7, 
        title:"Aspidistra Variegada", 
        price:"6500", 
        description:"", 
        image:"aspidistravariegada.jpg", 
        stock: 18,
        category:1
    },
    {
        id:8, 
        title:"Bacopa", 
        price:"5540", 
        description:"", 
        image:"bacopa.jpg",
        stock: 11,
        category:1
    },
    {
        id:9, 
        title:"Begonia", 
        price:"5590", 
        description:"", 
        image:"begonia.jpg",
        stock: 1, 
        category:1
    },
    {
        id:10, 
        title:"Begonia Dragon Wing", 
        price:"6500", 
        description:"", 
        image:"begoniadragonwing.jpg", 
        stock: 5, 
        category:1
    },
    {
        id:11, 
        title:"Cactus Grusonii", 
        price:"120000", 
        description:"", 
        image:"cactusgrusonii.jpg",
        stock: 7,  
        category:1
    },
    {
        id:12, 
        title:"Cactus injertado", 
        price:"12000", 
        description:"", 
        image:"cactusinjertado.jpg", 
        stock: 9, 
        category:1
    },
    {
        id:13, 
        title:"Cactus San Pedro", 
        price:"8000", 
        description:"", 
        image:"cactussanpedro.jpg",
        stock: 11,  
        category:1
    },
    {
        id:14, 
        title:"Caladium Rojo", 
        price:"18000", 
        description:"", 
        image:"caladiumrojo.jpg",
        stock: 13,  
        category:1
    },
    {
        id:15, 
        title:"Calathea Insignis", 
        price:"20000", 
        description:"", 
        image:"calatheainsignis.jpg",
        stock: 2,  
        category:1
    },
    {id:16, title:"Calathea Makoyana", price:"21000", description:"", image:"calatheamakoyana.jpg", stock: 7, category:1},
    {id:17, title:"Chamaedorea elegans", price:"13500", description:"", image:"chamaedoreaelegans.jpg", stock: 19, category:1},
    {id:18, title:"Cica", price:"4500", description:"", image:"cica.jpg", stock: 9, category:1},
    {id:19, title:"Cissus", price:"6000", description:"", image:"cissus.jpg", stock: 17, category:1},
    {id:20, title:"Coleo", price:"4800", description:"", image:"coleo.jpg", stock: 15, category:1},
    {id:21, title:"Crassula Arborescens", price:"2500", description:"", image:"crassulaarborescens.jpg", stock: 6, category:1},
    {id:22, title:"Crassula Ovata", price:"3000", description:"", image:"crassulaovata.jpg", stock: 9, category:1},
    {id:23, title:"Crassula Tetragona", price:"3500", description:"", image:"crassulatetragona.jpg", stock: 1, category:1},
    {id:24, title:"Croton", price:"4000", description:"", image:"croton.jpg", stock: 0, category:1},
    {id:25, title:"Cuerno de Alce", price:"15000", description:"", image:"cuernodealce.jpg", stock: 3, category:1},
    {id:26, title:"Delosperma de Lehmann", price:"3500", description:"", image:"delospermalehmannii.jpg", stock: 7, category:1},
    {id:27, title:"Dieffenbachia", price:"4500", description:"", image:"dieffenbachia.jpg", stock: 12, category:1},
    {id:28, title:"Dipladenia", price:"12000", description:"", image:"dipladenia.jpg", stock: 4, category:1},
    {id:29, title:"Dólar Blanco", price:"8000", description:"", image:"dolarblanco.jpg", stock: 5, category:1},
    {id:30, title:"Dólar Negro", price:"6000", description:"", image:"dolarnegro.jpg", stock: 0, category:1},
    {id:31, title:"Dólar Variegado", price:"6000", description:"", image:"dolarvariegado.jpg", stock: 0, category:1},
    {id:32, title:"Dólar Verde", price:"6000", description:"", image:"dolarverde.jpg", stock: 1, category:1},
    {id:33, title:"Dracena Lemon", price:"7500", description:"", image:"dracenalimon.jpg", stock: 3, category:1},
    {id:34, title:"Dracena Multicolor", price:"12000", description:"", image:"dracenamulticolor.jpg", stock: 2, category:1},
    {id:35, title:"Dracena Verde", price:"10500", description:"", image:"dracenaverde.jpg", stock: 6, category:1},
    {id:36, title:"Echeveria Agavoides", price:"3500", description:"", image:"echeveriaagavoides.jpg", stock: 4, category:1},
    {id:37, title:"Tierra de hoja orgánica 8L", price:"2000", description:"8L", image:"tierradehoja.jpg", stock: 12, category:2},
    {id:38, title:"Tierra de hoja orgánica 40L", price:"4000", description:"40L", image:"tierradehoja.jpg", stock: 4, category:2},
    {id:39, title:"Sustrato plantas de interior 3L", price:"2500", description:"3L", image:"sustratos.jpg", stock: 3, category:2},
    {id:40, title:"Sustrato plantas de interior 10L", price:"12500", description:"10L", image:"sustratos.jpg", stock: 10, category:3},
    {id:41, title:"Sustrato plantas de interior 50L", price:"17500", description:"50L", image:"sustratos.jpg", category:3},
    {id:42, title:"Macetero Balcón Doble", price:"2700", description:"Varios colores", image:"balcondoble.jpg", stock: 2, category:4},
    {id:43, title:"Macetero Animales", price:"3800", description:"Zorro", image:"zorro.jpg", stock: 10, category:4},
    {id:44, title:"Macetero Animales", price:"3800", description:"Perezoso", image:"perezoso.jpg", stock: 10, category:4},
    {id:45, title:"Macetero Animales", price:"3800", description:"Perrito", image:"perrito.jpg", stock: 9, category:4},
    {id:46, title:"Macetero Animales", price:"3800", description:"Gato", image:"gato.jpg", stock: 8, category:4},
    {id:47, title:"Macetero Animales", price:"4500", description:"Elefante", image:"elefante.jpg", stock: 12, category:4},
    {id:48, title:"Macetero Y87", price:"3500", description:"Macetero de plástico. Colores disponibles: Blanco y Gris", image:"y87.jpg", stock: 7, category:4},
    {id:49, title:"Macetero Y97-5", price:"4500", description:"Macetero de plástico. Colores disponibles: Blanco y gris", image:"y97-5.jpg", stock: 17, category:4},
    {id:50, title:"Macetero Y125-2", price:"2500", description:"Macetero de plástico. Colores disponibles: Gris", image:"y125-2.jpg", stock: 4, category:4},
    {id:51, title:"Macetero Y125-4", price:"3000", description:"Macetero de plástico. Colores disponibles: Rosa pálido", image:"y125-4.jpg", stock: 5, category:4},
    {id:52, title:"Macetero Y132", price:"5500", description:"Macetero de plástico. Colores disponibles: Blanco", image:"y132.jpg", stock: 6, category:4},
    {id:53, title:"Macetero Y97-4", price:"3500", description:"Macetero de plástico. Colores disponibles: Turquesa", image:"y97-4.jpg", stock: 8, category:4}
];